"""Test delete

Revision ID: 978378ab3b8f
Revises: 9cab7da19dac
Create Date: 2024-11-28 07:07:51.183180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '978378ab3b8f'
down_revision = '9cab7da19dac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'test')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
